import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
df = pd.read_csv(r'C:\\Users\\USER\\Documents\\main flow\\heart.csv')
print("data cleaning")
df.fillna(df.mean(), inplace=True)
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df_clean = df[~((df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]
print("Exploratory Data Analysis")
print(df_clean.info())
print(df_clean.describe())
plt.figure(figsize=(10,6))
sns.heatmap(df_clean.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()
sns.countplot(df_clean['target'])
plt.title("Distribution of Heart Disease Cases")
plt.show()
print("Question Formulation and Analysis")
print("What is the relationship between age and heart disease?")
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='age', hue='target', multiple='stack', bins=30)
plt.title('Age Distribution by Heart Disease')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()
print("Does gender (sex) have an impact on heart disease occurrence?")
plt.figure(figsize=(8, 5))
sns.countplot(x='sex', hue='target', data=df)
plt.title('Gender vs Heart Disease')
plt.xlabel('Gender (0 = Female, 1 = Male)')
plt.ylabel('Count')
plt.legend(title='Heart Disease (1 = Yes, 0 = No)')
plt.show()
print("How does chest pain type (cp) correlate with heart disease?")
plt.figure(figsize=(10, 6))
sns.countplot(x='cp', hue='target', data=df)
plt.title('Chest Pain Type vs Heart Disease')
plt.xlabel('Chest Pain Type')
plt.ylabel('Count')
plt.legend(title='Heart Disease (1 = Yes, 0 = No)')
plt.show()
print("What is the effect of resting blood pressure (trestbps) on heart disease?")
plt.figure(figsize=(10, 6))
sns.boxplot(x='target', y='trestbps', data=df)
plt.title('Resting Blood Pressure vs Heart Disease')
plt.xlabel('Heart Disease (1 = Yes, 0 = No)')
plt.ylabel('Resting Blood Pressure')
plt.show()
print("How do cholesterol levels (chol) vary with heart disease?")
plt.figure(figsize=(10, 6))
sns.boxplot(x='target', y='chol', data=df)
plt.title('Cholesterol Level vs Heart Disease')
plt.xlabel('Heart Disease (1 = Yes, 0 = No)')
plt.ylabel('Cholesterol Level')
plt.show()
print("Does fasting blood sugar (fbs) indicate heart disease?")
plt.figure(figsize=(8, 5))
sns.countplot(x='fbs', hue='target', data=df)
plt.title('Fasting Blood Sugar vs Heart Disease')
plt.xlabel('Fasting Blood Sugar (0 = < 120 mg/dl, 1 = > 120 mg/dl)')
plt.ylabel('Count')
plt.legend(title='Heart Disease (1 = Yes, 0 = No)')
plt.show()
print("Does exercise-induced angina (exang) indicate heart disease?")
plt.figure(figsize=(8, 5))
sns.countplot(x='exang', hue='target', data=df)
plt.title('Exercise-Induced Angina vs Heart Disease')
plt.xlabel('Exercise-Induced Angina (0 = No, 1 = Yes)')
plt.ylabel('Count')
plt.legend(title='Heart Disease (1 = Yes, 0 = No)')
plt.show()